### ISSUE TITLE
Logging shows itself as the origin of the log message

### ISSUE THREAD

**Issue by tklae** [uitsmijter/Uitsmijter#16]
In debug mode, the logger shows the origin of a log message, which is nice during development.

Unfortunately, sometimes the log line shows the logger class itself as the origin of the message instead of the code location from which it is logged.

The following test shows the misbehavior: 

```
    func testLogFromThisFunction() {
        Log.debug("Log from testLogFromThisFunction")
        XCTAssertContains(LogWriter.lastLog?.function, #function)
    }
```
 
Since `XCTAssertContains(LogWriter.lastLog?.function, #function)` is called by the function `testLogFromThisFunction` and `#function` is therefore `testLogFromThisFunction()`, the log should list this function accordingly. 

In reality, `debug(_:request:)` is printed to console and the test fails: 
```
XCTAssertTrue failed - debug(_:request:) does not contain testLogFromThisFunction()
```

Actual behavior:
```
[DEBUG] Mon, 11 Mar 2024 13:16:37 GMT: Log from testLogFromThisFunction[:] | debug(_:request:)in Server/Log.swift:98
```

Expected behavior: 
```
[DEBUG] Mon, 11 Mar 2024 13:16:37 GMT: Log from testLogFromThisFunction[:] | testLogFromThisFunction() in ServerTests/MyDemoTesT.swift:11
```

All log messages that are logged by the supplied logger action have this problem. Log messages that are delegated to a submodule do not have this problem (as you can see if you run the AppTest and compare the logs of vapor and those 
of uitsmijter's server package).

Tested on: 
~ Branch: main | Version: ce-0.9.5-10-g93a1ddb

**Comment by KrisSimon** [comment]
Hi @tklae 
Thank you for reporting the problem. I have had a quick look and can confirm your findings. A more detailed investigation and a quick fix is planned.

**Comment by KrisSimon** [comment]
Open Branch `feature/16-logging-shows-itself-as-the-origin-of-the-log-message`
Add tests `Logging/LoggingDebugFunctionsTest` to show the behaviour in each log level.
